<?php

namespace App\Http\Requests;

use App\Models\Logs;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Request;

class AuthorisationFormRequest extends FormRequest
{
    protected $stopOnFirstFailure = true;

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'email' => 'required|email',
            'password' => 'required'
        ];
    }

    public function messages()
    {
        return [
            'email.required' => 'Электронная почта обязательна к заполнению',
            'email.email' => 'Электронная почта введена не корректно',
            'password.required' => 'Пароль обязателен к заполнению',
        ];
    }

    public function failedValidation(Validator $validator)
    {
        $error = $validator->errors()->first();

        $log =
            [
                'action' => 'authorization',
                'response' => $error,
                'ip' => Request::getClientIp()
            ];

        Logs::insert($log);

        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
