<?php

namespace App\Http\Requests;

use App\Models\Logs;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Request;

class RegistrationFormRequest extends FormRequest
{
    protected $stopOnFirstFailure = true;

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'firstname' => 'required',
            'lastname' => 'required',
            'email' => 'required|email',
            'password' => 'required|same:repeat_password',
            'repeat_password' => 'required|same:password'
        ];
    }

    public function messages()
    {
        return [
            'firstname.required' => 'Имя обязательно к заполнению',
            'lastname.required' => 'Фамилия обязательна к заполнению',
            'email.required' => 'Электронная почта обязательна к заполнению',
            'email.email' => 'Электронная почта введена не корректно',
            'password.required' => 'Пароль обязателен к заполнению',
            'password.same' => 'Пароль не совпадает с повтором',
            'repeat_password.required' => 'Повторите введеный пароль',
        ];
    }

    public function failedValidation(Validator $validator)
    {
        $error = $validator->errors()->first();

        $log =
            [
                'action' => 'registration',
                'response' => $error,
                'ip' => Request::getClientIp()
            ];

        Logs::insert($log);

        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
